name: Generate snake animation

on:
  schedule:
    # Runs every 12 hours (UTC)
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to push to the output branch
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          # uses the owner of the repository running the workflow
          github_user_name: ${{ github.siddiq2604 }}
          outputs: |
            dist/snake.svg

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
